### ISSUE TITLE
Cannot put the new pandas dataframe into sqlite table

### ISSUE THREAD

**Issue by ytan15** [arfc/webscraping#6]
Hi Dr. @katyhuff ! As mentioned earlier today, seems like the code     
```
CREATE TABLE testTable(
        'index', 'Name' TEXT, 'Coord' TEXT, 'Long' REAL, 'Lat' REAL
    )
    '''
```
(lines 84-86 in https://github.com/ytan15/webscraping/blob/master/scraping_wikidata.py)
is not working. The error messages says "probably unsupported type".

Earlier it was 

```
CREATE TABLE testTable(
        'index', 'Name' OBJECT, 'Coord' OBJECT
    )
    '''
```
and it was working fine. 
Can you please take a look at it? Thanks!

**Comment by katyhuff** [comment]
Please copy and paste the full error message that you are getting.

**Comment by ytan15** [comment]
Traceback (most recent call last):
  File "scraping_wikidata.py", line 95, in <module>
    into_sql(df)
  File "scraping_wikidata.py", line 90, in into_sql
    df.to_sql(name = 'testTable', con = conn, if_exists = 'append', index = True)
  File "/Users/yukuntan/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1201, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "/Users/yukuntan/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 470, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "/Users/yukuntan/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1503, in to_sql
    table.insert(chunksize)
  File "/Users/yukuntan/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 664, in insert
    self._execute_insert(conn, keys, chunk_iter)
  File "/Users/yukuntan/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1291, in _execute_insert
    conn.executemany(self.insert_statement(), data_list)
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.

**Comment by katyhuff** [comment]
So, the problem was with the type of "Coord" which remaind "Object" rather than "text". There are a couple of ways around this. One is to recast that column as a string. However, it didn't seem like we really needed to keep that coord column around anyway, since the lat and lon can reconstruct it. So, the other alternative is to just drop that column from the dataframe. See https://github.com/ytan15/webscraping/pull/2 .
